name: librepcb
title: LibrePCB
base: core22
icon: snap/gui/librepcb.svg
version: 1.1.0-2
license: GPL-3.0+
website: https://librepcb.org
donation: https://librepcb.org/donate/
source-code: https://github.com/LibrePCB/LibrePCB
issues: https://github.com/LibrePCB/LibrePCB/issues
summary: EDA software to develop printed circuit boards.
description: |
  LibrePCB is a free EDA software to draw schematics and design printed
  circuit boards (PCBs).

  Key Features:

    - Cross-platform (Unix/Linux, Mac OS X, Windows)
    - All-in-one (project management, library/schematic/board editors)
    - Intuitive, modern and easy-to-use graphical user interface
    - Very powerful library design with some innovative concepts
    - Human-readable file formats
    - Open Source (GNU GPLv3)

  To get started with LibrePCB, please take a look at
  https://librepcb.org/docs/.

grade: stable
confinement: strict

apps:
  librepcb:
    command: bin/desktop-launch $SNAP/usr/local/bin/librepcb
    desktop: usr/local/share/applications/org.librepcb.LibrePCB.desktop
    environment:
      # Do not use Wayland for now because the 3D viewer contains very ugly
      # rendering artifacts. In addition, Wayland does not support
      # QWindow::requestActivate() which is used for switching windows.
      DISABLE_WAYLAND: 1
      # Set default workspace path to *outside* the (volatile) snap directory!
      # See https://github.com/LibrePCB/LibrePCB/pull/905.
      LIBREPCB_DEFAULT_WORKSPACE_PATH: "$SNAP_REAL_HOME/LibrePCB-Workspace"
      # Fix local files/directories not being opened.
      # See https://bugreports.qt.io/browse/QTBUG-83939.
      LIBREPCB_OPEN_URL_HANDLER: "/bin/xdg-open"
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - removable-media
      - wayland
      - x11
  librepcb-cli:
    command: bin/desktop-launch $SNAP/usr/local/bin/librepcb-cli
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - removable-media
      - wayland
      - x11

parts:
  patches:
    source: patches
    plugin: dump
    prime: [-*]
  librepcb:
    after: [patches, opencascade, desktop-qt5]
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr/local"
    build-environment:
      # Snapcraft prefixes PATH with something that makes cmake to fail
      # finding OpenCascade. We revert this by moving more important paths
      # to the front of PATH.
      - PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
    source: https://github.com/LibrePCB/LibrePCB.git
    source-tag: 1.1.0
    override-build: |
      git -C $CRAFT_PART_SRC checkout -- .
      git -C $CRAFT_PART_SRC apply $CRAFT_STAGE/*.patch
      craftctl default
    build-packages:
      - build-essential
      - libglu1-mesa-dev
      - libqt5opengl5-dev
      - libqt5svg5-dev
      - libsfml-dev
      - ninja-build
      - openssl
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - zlib1g
      - zlib1g-dev
    stage-packages:
      - libglu1-mesa
      - libqt5opengl5
      - libqt5printsupport5
      - libqt5quick5
      - libqt5quickcontrols2-5
      - libqt5sql5
      - libqt5sql5-sqlite
      - libqt5svg5
      - libqt5xml5
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick2
      - qt5-image-formats-plugins
      - qttranslations5-l10n  # to get translations for Qt built-in strings
      - qtwayland5
  # Using an OpenCascade version which is known to be working well with
  # LibrePCB, not just the one from the Ubuntu repositories because many
  # versions of OpenCascade do not work well.
  opencascade:
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DINSTALL_DIR=/usr"
      - "-DBUILD_LIBRARY_TYPE=Shared"
      - "-DBUILD_MODULE_ApplicationFramework=0"
      - "-DBUILD_MODULE_DataExchange=1"
      - "-DBUILD_MODULE_Draw=0"
      - "-DBUILD_MODULE_FoundationClasses=0"
      - "-DBUILD_MODULE_ModelingAlgorithms=0"
      - "-DBUILD_MODULE_ModelingData=0"
      - "-DBUILD_MODULE_Visualization=0"
      - "-DUSE_DRACO=0"
      - "-DUSE_FREEIMAGE=0"
      - "-DUSE_FREETYPE=0"
      - "-DUSE_GLES2=0"
      - "-DUSE_OPENGL=0"
      - "-DUSE_OPENVR=0"
      - "-DUSE_RAPIDJSON=0"
      - "-DUSE_TBB=0"
      - "-DUSE_TK=0"
      - "-DUSE_VTK=0"
    source: https://github.com/Open-Cascade-SAS/OCCT/archive/refs/tags/V7_7_2.tar.gz
    # Workaround to fix a CMake/OpenCascade error...
    override-build: |
      snapcraftctl build
      sed -i 's:\\${OCCT_INSTALL_BIN_LETTER}::g' $SNAPCRAFT_PART_INSTALL/usr/lib/cmake/opencascade/OpenCASCADE*.cmake
    build-packages:
      - build-essential
      - ninja-build
  desktop-qt5:
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - fonts-freefont-ttf
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
