name: librepcb
base: core18
adopt-info: librepcb
summary: EDA software to develop printed circuit boards.
description: |
  LibrePCB is a free EDA software to draw schematics and design printed
  circuit boards (PCBs).

  Key Features:

    - Cross-platform (Unix/Linux, Mac OS X, Windows)
    - All-in-one (project management, library/schematic/board editors)
    - Intuitive, modern and easy-to-use graphical user interface
    - Very powerful library design with some innovative concepts
    - Human-readable file formats
    - Open Source (GNU GPLv3)

  To get started with LibrePCB, please take a look at
  https://docs.librepcb.org/.

grade: stable
confinement: strict

apps:
  librepcb:
    command: desktop-launch $SNAP/usr/local/bin/librepcb
    environment:
      # Do not use Wayland for now since it looks ugly. Copied from MuseScore:
      # https://github.com/pachulo/musescore-snap/blob/master/snap/snapcraft.yaml
      DISABLE_WAYLAND: 1
      QT_QPA_PLATFORMTHEME: gtk3
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - removable-media
      - wayland
      - x11
  librepcb-cli:
    command: desktop-launch $SNAP/usr/local/bin/librepcb-cli
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - removable-media
      - wayland
      - x11

parts:
  librepcb:
    after: [desktop-qt5]
    plugin: qmake
    qt-version: qt5
    source: https://github.com/LibrePCB/LibrePCB.git
    source-commit: a435c5095c6f94df4da130fe832ea97f42d17901
    # Note: snapcraft does not check out the correct submodule revisions, so
    # we manually need to run "git submodule update --init --recursive".
    override-pull: |
      snapcraftctl pull
      git submodule update --init --recursive
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "0.1.5-2"
    project-files: ["librepcb.pro"]
    options: ["-r"]
    build-packages:
      - qt5-default
      - qttools5-dev-tools
      - build-essential
      - libglu1-mesa-dev
      - openssl
      - zlib1g
      - zlib1g-dev
      - libqt5svg5-dev
      - libqt5opengl5-dev
      - libsfml-dev
    stage-packages:
      - libglu1-mesa
      - libqt5opengl5
      - libqt5printsupport5
      - libqt5svg5
      - libqt5sql5
      - libqt5sql5-sqlite
      - qttranslations5-l10n  # to get translations for Qt built-in strings
      - qtwayland5
  desktop-qt5:
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    make-parameters:
    - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5
    - try:
      - appmenu-qt5
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5
