name: librepcb
title: LibrePCB
base: core22
icon: snap/gui/librepcb.svg
version: 1.0.0-rc1-1
license: GPL-3.0+
website: https://librepcb.org
donation: https://librepcb.org/donate/
source-code: https://github.com/LibrePCB/LibrePCB
issues: https://github.com/LibrePCB/LibrePCB/issues
summary: EDA software to develop printed circuit boards.
description: |
  LibrePCB is a free EDA software to draw schematics and design printed
  circuit boards (PCBs).

  Key Features:

    - Cross-platform (Unix/Linux, Mac OS X, Windows)
    - All-in-one (project management, library/schematic/board editors)
    - Intuitive, modern and easy-to-use graphical user interface
    - Very powerful library design with some innovative concepts
    - Human-readable file formats
    - Open Source (GNU GPLv3)

  To get started with LibrePCB, please take a look at
  https://librepcb.org/docs/.

grade: stable
confinement: strict

apps:
  librepcb:
    command: bin/desktop-launch $SNAP/usr/local/bin/librepcb
    environment:
      # Do not use Wayland for now because the 3D viewer contains very ugly
      # rendering artifacts. In addition, Wayland does not support
      # QWindow::requestActivate() which is used for switching windows.
      DISABLE_WAYLAND: 1
      # Set default workspace path to *outside* the (volatile) snap directory!
      # See https://github.com/LibrePCB/LibrePCB/pull/905.
      LIBREPCB_DEFAULT_WORKSPACE_PATH: "$SNAP_REAL_HOME/LibrePCB-Workspace"
      # Fix local files/directories not being opened.
      # See https://bugreports.qt.io/browse/QTBUG-83939.
      LIBREPCB_OPEN_URL_HANDLER: "/bin/xdg-open"
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - removable-media
      - wayland
      - x11
  librepcb-cli:
    command: bin/desktop-launch $SNAP/usr/local/bin/librepcb-cli
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - removable-media
      - wayland
      - x11

parts:
  patches:
    source: patches
    plugin: dump
    prime: [-*]
  librepcb:
    after: [patches, desktop-qt5]
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr/local"
    source: https://github.com/LibrePCB/LibrePCB.git
    source-tag: 1.0.0-rc1
    override-build: |
      git -C $CRAFT_PART_SRC apply $CRAFT_STAGE/*.patch
      craftctl default
    build-packages:
      - build-essential
      - libglu1-mesa-dev
      - liboce-ocaf-dev
      - libqt5opengl5-dev
      - libqt5svg5-dev
      - libsfml-dev
      - ninja-build
      - openssl
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - zlib1g
      - zlib1g-dev
    stage-packages:
      - libglu1-mesa
      - liboce-ocaf11
      - libqt5opengl5
      - libqt5printsupport5
      - libqt5quick5
      - libqt5quickcontrols2-5
      - libqt5sql5
      - libqt5sql5-sqlite
      - libqt5svg5
      - libqt5xml5
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick2
      - qttranslations5-l10n  # to get translations for Qt built-in strings
      - qtwayland5
  desktop-qt5:
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - fonts-freefont-ttf
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
