name: librepcb
title: LibrePCB
base: core24
icon: snap/gui/librepcb.svg
version: 2.0.0-rc1-1  # Always append a deployment version (e.g. "-1")
license: GPL-3.0+
website: https://librepcb.org
donation: https://librepcb.org/donate/
source-code: https://github.com/LibrePCB/LibrePCB
issues: https://github.com/LibrePCB/LibrePCB/issues
contact: https://librepcb.org/contact/
summary: EDA software to develop printed circuit boards.
description: |
  LibrePCB is a free EDA software to draw schematics and design printed
  circuit boards (PCBs).

  Key Features:

    - Cross-platform (Unix/Linux, Mac OS X, Windows)
    - All-in-one (project management, library/schematic/board editors)
    - Intuitive, modern and easy-to-use graphical user interface
    - Very powerful library design with some innovative concepts
    - Human-readable file formats
    - Open Source (GNU GPLv3)

  To get started with LibrePCB, please take a look at
  https://librepcb.org/docs/.

grade: stable
confinement: strict

# See https://github.com/ubuntu/snapcraft-desktop-helpers/pull/227#issuecomment-2694314156
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy

apps:
  librepcb:
    command: bin/desktop-launch $SNAP/usr/bin/librepcb
    desktop: usr/share/applications/org.librepcb.LibrePCB.desktop
    environment:
      # Fix "error while loading shared libraries: libpxbackend-1.0.so".
      # See https://github.com/ubuntu/snapcraft-desktop-helpers/pull/227#issuecomment-2694314156.
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio
      # Do not use Wayland for now because the 3D viewer contains very ugly
      # rendering artifacts. In addition, Wayland does not support
      # QWindow::requestActivate() which is used for switching windows.
      DISABLE_WAYLAND: 1
      # Set default workspace path to *outside* the (volatile) snap directory!
      # See https://github.com/LibrePCB/LibrePCB/pull/905.
      LIBREPCB_DEFAULT_WORKSPACE_PATH: "$SNAP_REAL_HOME/LibrePCB-Workspace"
      # Fix local files/directories not being opened.
      # See https://bugreports.qt.io/browse/QTBUG-83939.
      LIBREPCB_OPEN_URL_HANDLER: "/bin/xdg-open"
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - removable-media
      - wayland
      - x11
  librepcb-cli:
    command: bin/desktop-launch $SNAP/usr/bin/librepcb-cli
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - removable-media
      - wayland
      - x11

parts:
  librepcb:
    after: [opencascade, desktop-qt, rust-toolchain]
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    build-environment:
      # Snapcraft prefixes PATH with something that makes cmake to fail
      # finding OpenCascade. We revert this by moving more important paths
      # to the front of PATH.
      - PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
    source: https://github.com/LibrePCB/LibrePCB.git
    source-tag: 2.0.0-rc1
    build-packages:
      - build-essential
      - libglu1-mesa-dev
      - libqt6opengl6-dev
      - libqt6svg6-dev
      - libsfml-dev
      - ninja-build
      - openssl
      - qt6-base-dev
      - qt6-l10n-tools
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - zlib1g
      - zlib1g-dev
    stage-packages:
      - libglu1-mesa
      - libglu1-mesa-dev
      - libproxy1v5
      - libqt6opengl6t64
      - libqt6openglwidgets6t64
      - libqt6printsupport6t64
      - libqt6sql6t64
      - libqt6sql6-sqlite
      - libqt6svg6
      - libqt6xml6t64
      - libxcb-xinerama0
      - qt6-image-formats-plugins
      - qt6-qpa-plugins
      - qt6-translations-l10n  # to get translations for Qt built-in strings
      - qt6-wayland
      - qt6-xdgdesktopportal-platformtheme
  # Using an OpenCascade version which is known to be working well with
  # LibrePCB, not just the one from the Ubuntu repositories because many
  # versions of OpenCascade do not work well.
  opencascade:
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DINSTALL_DIR=/usr"
      - "-DBUILD_LIBRARY_TYPE=Shared"
      - "-DBUILD_MODULE_ApplicationFramework=0"
      - "-DBUILD_MODULE_DataExchange=1"
      - "-DBUILD_MODULE_Draw=0"
      - "-DBUILD_MODULE_FoundationClasses=0"
      - "-DBUILD_MODULE_ModelingAlgorithms=0"
      - "-DBUILD_MODULE_ModelingData=0"
      - "-DBUILD_MODULE_Visualization=0"
      - "-DUSE_DRACO=0"
      - "-DUSE_FREEIMAGE=0"
      - "-DUSE_FREETYPE=0"
      - "-DUSE_GLES2=0"
      - "-DUSE_OPENGL=0"
      - "-DUSE_OPENVR=0"
      - "-DUSE_RAPIDJSON=0"
      - "-DUSE_TBB=0"
      - "-DUSE_TK=0"
      - "-DUSE_VTK=0"
    source: https://github.com/Open-Cascade-SAS/OCCT/archive/refs/tags/V7_9_1.tar.gz
    # Workaround to fix a CMake/OpenCascade error...
    override-build: |
      snapcraftctl build
      sed -i 's:\\${OCCT_INSTALL_BIN_LETTER}::g' $SNAPCRAFT_PART_INSTALL/usr/lib/cmake/opencascade/OpenCASCADE*.cmake
    build-packages:
      - build-essential
      - ninja-build
  desktop-qt:
    source: snap/local/snapcraft-desktop-helpers
    source-subdir: qt
    source-type: local
    plugin: make
    make-parameters:
      - FLAVOR=qt6
    build-packages:
      - build-essential
      - dpkg-dev
      - qt6-base-dev
      - software-properties-common
    stage-packages:
      - adwaita-icon-theme
      - dmz-cursor-theme
      - fonts-ubuntu
      - gnome-themes-extra
      - gsettings-desktop-schemas
      - libgdk-pixbuf2.0-0
      - libglib2.0-0t64
      - libglib2.0-bin
      - libglib2.0-data
      - libgtk-3-common
      - libgtk2.0-0t64
      - libqt6gui6t64
      - libqt6svg6 # for loading icon themes which are svg
      - libxkbcommon0
      - light-themes
      - locales-all
      - qt6-qpa-plugins
      - qt6-wayland
      - shared-mime-info
      - xdg-user-dirs
      - xkb-data
  rust-toolchain:
    plugin: nil
    build-packages:
      - curl
    override-pull: >
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
      sh -s -- -y --default-toolchain 1.92.0 --profile minimal
