#!/bin/sh

LOG=$SNAP_COMMON/install_hook_log.txt
echo `date` > $LOG

cp -vf $SNAP/usr/local/share/mime/packages/org.librepcb.LibrePCB.xml \
 /usr/local/share/mime/packages/librepcb-snap.xml >> $LOG
update-mime-database /usr/local/share/mime >> $LOG
