#!/bin/sh

LOG=$SNAP_COMMON/install_hook_log.txt
echo `date` > $LOG

mkdir -vp /usr/share/mime/packages >> $LOG
cp -vf $SNAP/usr/local/share/mime/packages/org.librepcb.LibrePCB.xml \
 /usr/share/mime/packages/librepcb-snap.xml >> $LOG
update-mime-database /usr/share/mime >> $LOG
